export const USER_REPOSITORY_TOKEN = 'USER_REPOSITORY_TOKEN';
export const USER_PASSWORD_REPOSITORY_TOKEN = 'USER_PASSWORD_REPOSITORY_TOKEN';
export const DB_CONNECTION_TOKEN = 'DB_CONNECTION_TOKEN';
export const HASHING_ALGORITHM = 'bcrypt';
export const PASSWORD_CRYPTOGRAPHER_TOKEN = 'PASSWORD_CRYPTOGRAPHER_TOKEN';
export const EMAIL_VALIDATOR_TOKEN = 'EMAIL_VALIDATOR_TOKEN';
